//-----------------------------------------------------------------------------
//     _____          __  .__      ___________     ___.   .__            v1.4.1   
//    /     \ _____ _/  |_|  |__   \__    ___/____ \_ |__ |  |   ____          
//   /  \ /  \\__  \\   __\  |  \    |    |  \__  \ | __ \|  | _/ __ \         
//  /    Y    \/ __ \|  | |   Y  \   |    |   / __ \| \_\ \  |_\  ___/         
//  \____|__  (____  /__| |___|  /   |____|  (____  /___  /____/\___  >        
//          \/     \/          \/                 \/    \/          \/         
//  by Guillaume "Aoineko" Blanchard (aoineko@free.fr) under CC-BY-AS license
//                                                                             
// Generated: Sat Nov 14 23:31:30 2020
// Parameters: Entries=64, Bytes=2 (16-bits), Shift=8 (Q8.8)               
//-----------------------------------------------------------------------------

// ArcSinus table. Range [-1:1]
static const unsigned short g_ArcSinus64[65] =
{
	0xFE6E, 0xFEAF, 0xFEC9, 0xFEDE, 0xFEF0, 0xFEFF, 0xFF0E, 0xFF1B, 
	0xFF27, 0xFF33, 0xFF3E, 0xFF49, 0xFF54, 0xFF5E, 0xFF68, 0xFF71, 
	0xFF7A, 0xFF84, 0xFF8D, 0xFF95, 0xFF9E, 0xFFA7, 0xFFAF, 0xFFB8, 
	0xFFC0, 0xFFC8, 0xFFD0, 0xFFD8, 0xFFE0, 0xFFE8, 0xFFF0, 0xFFF8, 
	0x0000, 0x0008, 0x0010, 0x0018, 0x0020, 0x0028, 0x0030, 0x0038, 
	0x0040, 0x0048, 0x0051, 0x0059, 0x0062, 0x006B, 0x0073, 0x007C, 
	0x0086, 0x008F, 0x0098, 0x00A2, 0x00AC, 0x00B7, 0x00C2, 0x00CD, 
	0x00D9, 0x00E5, 0x00F2, 0x0101, 0x0110, 0x0122, 0x0137, 0x0151, 
	0x0192, 
};
